- Use setter/getter to set/access attributes of an instance
    - attributes should be made *private*
    - setter/getter are *public* method
    - the constructor might has no parameter, which could be convenient
- Enhanced for loop || Updating while looping an arrayList
    - use index loop instead if want to modify the arrayList
